In [1]:
from lxml import etree
from pathlib import Path
import random
import pandas as pd

from medical_rag.text_chunker import PubMedFullTextChunker
from medical_rag.config import parse_pmc

e:\anaconda3\envs\medrag\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 创建Metadata dataframe

In [2]:
xml_files = list(
    Path(
        r"E:\字节跳动算法实习\data\PMC\extracted"
    ).rglob("*.xml")
)

print(len(xml_files))

sample_files = random.sample(
    xml_files,
    30000
)

3242816

In [ ]:
# 创建dataframe来记录文献metadata

# 每批处理10000篇文献
batch_size = 10000

# 保存目录
output_dir = Path("F:/RAG/data/parsed_batches")
output_dir.mkdir(exist_ok=True)

records = []
batch_id = 0

for i, file in enumerate(sample_files):

    try:
        records.append(parse_pmc(file))

    except Exception as e:
        print(f"Skip {file}: {e}")

    # 满一个batch或者处理到最后一个文件
    if len(records) == batch_size or i == len(sample_files) - 1:

        # 创建DataFrame
        df_batch = pd.DataFrame(records)

        # 保存
        output_file = output_dir / f"batch_{batch_id:04d}.parquet"
        df_batch.to_parquet(output_file, index=False)

        print(f"Batch {batch_id} saved: {len(df_batch)} documents")

        # 清空内存
        records.clear()

        batch_id += 1

<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\xukeh\AppData\Local\Temp\ipykernel_32116\3551698894.py:7: SyntaxWarning: invalid escape sequence '\d'
  output_dir = Path("E:\字节跳动算法实习\data\parsed_batches")

Batch 0 saved: 10000 documents
Batch 1 saved: 10000 documents
Batch 2 saved: 10000 documents

In [3]:
# Parquet目录
parquet_dir = Path("F:/RAG/data/parsed_batches")

# 获取所有Parquet文件
parquet_files = sorted(parquet_dir.glob("*.parquet"))

print(f"Found {len(parquet_files)} parquet files.")

# 读取并合并
df = pd.concat(
    [pd.read_parquet(f) for f in parquet_files],
    ignore_index=True
)

print(df.shape)
df.head()

Found 3 parquet files.
(30000, 6)

,title,abstract,journal,pmid,pub_date,full_text
0,Common mental disorders and subjective well-be...,IntroductionThe prevalence of common mental di...,PLoS ONE,30731006,2019,"In the field of positive psychology, well-bein..."
1,Magnetization relaxation in the single-ion mag...,\nQuantum tunneling and relaxation of magnetiz...,Physical Chemistry Chemical Physics,29671443,2018,Hiding atomic clusters behind the walls of pro...
2,A New Method of Treating the Fistula Lachrymalis,,The London Medical Journal,29139655,1781,
3,Persistence of Transmitted HIV-1 Drug Resistan...,Transmission of drug-resistant pathogens prese...,PLoS Pathogens,25798934,2015,Drug-resistant pathogens represent one of the ...
4,Prenatal Exposure to Lipopolysaccharide Combin...,BackgroundAdult metabolic syndrome may in part...,PLoS ONE,24498431,2014,The pathophysiology of Type 2 diabetes (T2DM) ...

## 初始化文本分割器

In [4]:
#初始化文本分割器

chunker = PubMedFullTextChunker(
    tokenizer_name="deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    chunk_size=500,
    chunk_overlap=80,
    min_text_tokens=30,
    max_token_limit=512,
    add_title_to_each_chunk=True,
)

chunks_df, stats = chunker.split_dataframe(
    df_raw=df,
    full_text_col="full_text",
    output_path="E:\字节跳动算法实习\data\pubmed_fulltext_chunks.parquet",
    stats_path="E:\字节跳动算法实习\data\pubmed_fulltext_chunk_stats.json",
    data_split="pmc_full_text"
)

print(stats)

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (21839 > 16384). Running this sequence through the model will result in indexing errors
Splitting documents:   2%|▏         | 429/28246 [01:11<1:17:34,  5.98it/s]

KeyboardInterrupt:

## 预览分割结果

In [5]:
chunks_df = pd.read_parquet(
    "F:\RAG\data\pubmed_fulltext_chunks_2.parquet"
)

print(chunks_df.shape)
chunks_df.head()

(668461, 11)

,chunk_id,text,doc_id,chunk_index,total_chunks,source_title,journal,pub_date,pmid,token_count,split_strategy
0,PMID_30731006_chunk_0000,Title: Common mental disorders and subjective ...,PMID_30731006,0,17,Common mental disorders and subjective well-be...,PLoS ONE,2019,30731006,500,sliding_window
1,PMID_30731006_chunk_0001,Title: Common mental disorders and subjective ...,PMID_30731006,1,17,Common mental disorders and subjective well-be...,PLoS ONE,2019,30731006,487,sliding_window
2,PMID_30731006_chunk_0002,Title: Common mental disorders and subjective ...,PMID_30731006,2,17,Common mental disorders and subjective well-be...,PLoS ONE,2019,30731006,503,sliding_window
3,PMID_30731006_chunk_0003,Title: Common mental disorders and subjective ...,PMID_30731006,3,17,Common mental disorders and subjective well-be...,PLoS ONE,2019,30731006,491,sliding_window
4,PMID_30731006_chunk_0004,Title: Common mental disorders and subjective ...,PMID_30731006,4,17,Common mental disorders and subjective well-be...,PLoS ONE,2019,30731006,491,sliding_window

In [6]:
chunks_df.columns

Index(['chunk_id', 'text', 'doc_id', 'chunk_index', 'total_chunks',
       'source_title', 'journal', 'pub_date', 'pmid', 'token_count',
       'split_strategy'],
      dtype='object')

In [7]:
#chunk数量统计
print("Total chunks:", len(chunks_df))
print(
    "Total documents:",
    chunks_df["doc_id"].nunique()
)
print(
    "Average chunks/document:",
    len(chunks_df)
    /
    chunks_df["doc_id"].nunique()
)

Total chunks: 668461
Total documents: 28246
Average chunks/document: 23.665687176945408

In [8]:
#Token长度检查
print(
    "Maximum:",
    chunks_df["token_count"].max()
)

print(
    "95 percentile:",
    chunks_df["token_count"].quantile(0.95)
)
print(
    "Chunks with more than 512 tokens:",
    (chunks_df["token_count"] > 512).sum()
)

Maximum: 513
95 percentile: 512.0
Chunks with more than 512 tokens: 3

In [9]:
#split_strategy统计
chunks_df["split_strategy"].value_counts()

split_strategy
sliding_window    667879
no_split             582
Name: count, dtype: int64

## 多块文档检查

In [10]:
# 找出被分割成多个 chunk 的文献
multi_doc_ids = (
    chunks_df[chunks_df["total_chunks"] > 1]["doc_id"]
    .drop_duplicates()
)

print("Number of multi-chunk documents:", len(multi_doc_ids))
print("Rate:", len(multi_doc_ids) / chunks_df["doc_id"].nunique() * 100)

Number of multi-chunk documents: 27664
Rate: 97.93953126106352

In [11]:
#检查 chunk_index 是否连续
def check_chunk_index_continuity(group):
    indices = sorted(group["chunk_index"].tolist())
    expected = list(range(len(indices)))
    return indices == expected

continuity_report = (
    chunks_df.groupby("doc_id")
    .apply(check_chunk_index_continuity)
)

print("Documents with continuous chunk_index:", continuity_report.sum())
print("Documents with broken chunk_index:", (~continuity_report).sum())

Documents with continuous chunk_index: 28246
Documents with broken chunk_index: 0

C:\Users\xukeh\AppData\Local\Temp\ipykernel_27620\4017873602.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(check_chunk_index_continuity)

In [12]:
sample_multi_docs = multi_doc_ids.sample(
    min(5, len(multi_doc_ids)),
    random_state=42
)

for doc_id in sample_multi_docs:
    doc_chunks = (
        chunks_df[chunks_df["doc_id"] == doc_id]
        .sort_values("chunk_index")
    )

    print("=" * 120)
    print("doc_id:", doc_id)
    print("source_title:", doc_chunks.iloc[0]["source_title"])
    print("total_chunks:", doc_chunks.iloc[0]["total_chunks"])

    for _, row in doc_chunks.head(3).iterrows():
        print("-" * 80)
        print("chunk_index:", row["chunk_index"])
        print("chunk_id:", row["chunk_id"])
        print("token_count:", row["token_count"])
        print("text start:")
        print(row["text"][:300])
        print("text end:")
        print(row["text"][-300:])

========================================================================================================================
doc_id: DOC_d4ddb8a8944b
source_title: Anti-interleukin 1 treatment in secondary renal amyloidosis associated with autoinflammatory diseases
total_chunks: 2
--------------------------------------------------------------------------------
chunk_index: 0
chunk_id: DOC_d4ddb8a8944b_chunk_0000
token_count: 512
text start:
Title: Anti-interleukin 1 treatment in secondary renal amyloidosis associated with autoinflammatory diseases

Amyloidosis represents a heterogeneous group of disorders characterized by extracellular deposition of autologous fibrillary proteins which impair normal organ function. Reactive AA type amy
text end:
ment of amyloidosis, it is crucial to control inflammation effectively and prevent further amyloid accumulation in patients with anti-inflammatory treatments such as anti-IL1 drugs. However, new treatment strategies are needed to target the amyloid deposits for patients with severe organ involvement
--------------------------------------------------------------------------------
chunk_index: 1
chunk_id: DOC_d4ddb8a8944b_chunk_0001
token_count: 82
text start:
progression of renal tissue damage after the improvement of proteinuria with anti-IL 1 treatment in AID-associated amyloidosis. After the development of amyloidosis, it is crucial to control inflammation effectively and prevent further amyloid accumulation in patients with anti-inflammatory treatmen
text end:
ent of amyloidosis, it is crucial to control inflammation effectively and prevent further amyloid accumulation in patients with anti-inflammatory treatments such as anti-IL1 drugs. However, new treatment strategies are needed to target the amyloid deposits for patients with severe organ involvement.
========================================================================================================================
doc_id: PMID_34026006
source_title: Nutrient trade‐offs mediated by ectomycorrhizal strategies in plants: Evidence from an Abies species in subalpine forests
total_chunks: 30
--------------------------------------------------------------------------------
chunk_index: 0
chunk_id: PMID_34026006_chunk_0000
token_count: 512
text start:
Title: Nutrient trade‐offs mediated by ectomycorrhizal strategies in plants: Evidence from an Abies species in subalpine forests

Over 80% of tree species form ectomycorrhizal (ECM) symbionts, which are essential for maintenance of forest ecosystem health and effective soil nutrient uptakes by host
text end:
 are essential nutrient elements for plants and other organisms, but their limitations are common in terrestrial ecosystems. The uptake efficiency of N and P is dependent on the root systems with strategies adapting to environmental conditions (Chien et al., 2011; Hodge, 2004; Jackson & Caldwell, 19
--------------------------------------------------------------------------------
chunk_index: 1
chunk_id: PMID_34026006_chunk_0001
token_count: 83
text start:
016, 2018). Both N and P are essential nutrient elements for plants and other organisms, but their limitations are common in terrestrial ecosystems. The uptake efficiency of N and P is dependent on the root systems with strategies adapting to environmental conditions (Chien et al., 2011; Hodge, 2004
text end:
e essential nutrient elements for plants and other organisms, but their limitations are common in terrestrial ecosystems. The uptake efficiency of N and P is dependent on the root systems with strategies adapting to environmental conditions (Chien et al., 2011; Hodge, 2004; Jackson & Caldwell, 1996)
--------------------------------------------------------------------------------
chunk_index: 2
chunk_id: PMID_34026006_chunk_0002
token_count: 499
text start:
Title: Nutrient trade‐offs mediated by ectomycorrhizal strategies in plants: Evidence from an Abies species in subalpine forests

. Both N and P are essential nutrient elements for plants and other organisms, but their limitations are common in terrestrial ecosystems. The uptake efficiency of N and
text end:
igh leaf mass per unit area, especially the tree species in Pinaceae and Fagaceae families (Cornelissen et al., 2001; Koele et al., 2012; Read, 1991). The intimate connections of foliar N nutrition and ECM symbiosis are widely reported (Hobbie et al., 2005; Hobbie & Hobbie, 2006; Koele et al., 2012)
========================================================================================================================
doc_id: PMID_22140348
source_title: Larvae and a new species of Ancyronyx Erichson, 1847 (Insecta, Coleoptera, Elmidae) from Palawan, Philippines, using DNA sequences for the assignment of the developmental stages
total_chunks: 92
--------------------------------------------------------------------------------
chunk_index: 0
chunk_id: PMID_22140348_chunk_0000
token_count: 512
text start:
Title: Larvae and a new species of Ancyronyx Erichson, 1847 (Insecta, Coleoptera, Elmidae) from Palawan, Philippines, using DNA sequences for the assignment of the developmental stages

The genus Ancyronyx, usually referred to as spider water beetle, belongs to the predominantly aquatic riffle beetl
text end:
10 years. The copious collection of Ancyronyx specimens, both adult and larvae, retrieved by this taxonomic research initiative gave us the opportunity to study the larvae of this genus taxonomically for the first time. The larvae examined were partly collected by standardized methods for ecological
--------------------------------------------------------------------------------
chunk_index: 1
chunk_id: PMID_22140348_chunk_0001
token_count: 111
text start:
http://aquapalawana.nhm-wien.ac.at) conducted by the first author for more than 10 years. The copious collection of Ancyronyx specimens, both adult and larvae, retrieved by this taxonomic research initiative gave us the opportunity to study the larvae of this genus taxonomically for the first time.
text end:
his taxonomic research initiative gave us the opportunity to study the larvae of this genus taxonomically for the first time. The larvae examined were partly collected by standardized methods for ecological studies such as colonization and drift sampling during a survey in 2000 / 2001 (Freitag 2005)
--------------------------------------------------------------------------------
chunk_index: 2
chunk_id: PMID_22140348_chunk_0002
token_count: 501
text start:
Title: Larvae and a new species of Ancyronyx Erichson, 1847 (Insecta, Coleoptera, Elmidae) from Palawan, Philippines, using DNA sequences for the assignment of the developmental stages

. The larvae examined were partly collected by standardized methods for ecological studies such as colonization an
text end:
 (Fig. 2) using Qiagen DNeasy kit (Qiagen, Hilden, Germany) and a single elution following the protocol for animal tissues (Qiagen 2002). The 3’ end of the cytochrome c oxidase subunit I (cox1) gene was amplified using polymerase chain reaction (PCR) following standard protocols (e.g. Caterino et al
========================================================================================================================
doc_id: PMID_31501122
source_title: Tolerogenic dendritic cell-based treatment for multiple sclerosis (MS): a harmonised study protocol for two phase I clinical trials comparing intradermal and intranodal cell administration
total_chunks: 24
--------------------------------------------------------------------------------
chunk_index: 0
chunk_id: PMID_31501122_chunk_0000
token_count: 512
text start:
Title: Tolerogenic dendritic cell-based treatment for multiple sclerosis (MS): a harmonised study protocol for two phase I clinical trials comparing intradermal and intranodal cell administration

The concept of the clinical trials is built on recent advances in the understanding of tolerance induct
text end:
fic nor selective for MS, that is, they work in an immunomodulatory or immunosuppressive way by sequestering or depleting lymphocytes, although that some therapies can induce immune reconstitution as well. Moreover, treatment-related side effects or risks can be severe,4 leaving a significant and un
--------------------------------------------------------------------------------
chunk_index: 1
chunk_id: PMID_31501122_chunk_0001
token_count: 90
text start:
6.8 years in a recent cohort.3 Nonetheless, DMT are not specific nor selective for MS, that is, they work in an immunomodulatory or immunosuppressive way by sequestering or depleting lymphocytes, although that some therapies can induce immune reconstitution as well. Moreover, treatment-related side
text end:
omodulatory or immunosuppressive way by sequestering or depleting lymphocytes, although that some therapies can induce immune reconstitution as well. Moreover, treatment-related side effects or risks can be severe,4 leaving a significant and unmet need for safer and more disease-selective treatments
--------------------------------------------------------------------------------
chunk_index: 2
chunk_id: PMID_31501122_chunk_0002
token_count: 340
text start:
Title: Tolerogenic dendritic cell-based treatment for multiple sclerosis (MS): a harmonised study protocol for two phase I clinical trials comparing intradermal and intranodal cell administration

. Moreover, treatment-related side effects or risks can be severe,4 leaving a significant and unmet nee
text end:
ive and promising strategy for the treatment of autoimmunity. This approach is based on the possibility that autoreactive B and T cells, driving myelin destruction and damage in the CNS, will be eradicated by inducing tolerance to myelin-derived peptides, without interfering with protective immunity
========================================================================================================================
doc_id: PMID_28432303
source_title: Closed-loop deep brain stimulation by pulsatile delayed feedback with increased gap between pulse phases
total_chunks: 45
--------------------------------------------------------------------------------
chunk_index: 0
chunk_id: PMID_28432303_chunk_0000
token_count: 466
text start:
Title: Closed-loop deep brain stimulation by pulsatile delayed feedback with increased gap between pulse phases

Several neurological disorders like Parkinson’s disease (PD), essential tremor, epilepsy or tinnitus are characterized by abnormal neuronal synchronization1–7. High-frequency (HF) deep br
text end:
 networks30. In computational studies coordinated reset (CR) stimulation28, 29, a spatio-temporally patterned desynchronizing stimulation technique, turned out to decrease the rate of coincidences and, in turn, to reduce abnormal synaptic weights30, 33. CR stimulation may cause an anti-kindling, i.e
--------------------------------------------------------------------------------
chunk_index: 1
chunk_id: PMID_28432303_chunk_0001
token_count: 512
text start:
Title: Closed-loop deep brain stimulation by pulsatile delayed feedback with increased gap between pulse phases

. In computational studies coordinated reset (CR) stimulation28, 29, a spatio-temporally patterned desynchronizing stimulation technique, turned out to decrease the rate of coincidences a
text end:
 as electrical stimulation because of safety aspects like charge density limits18, 59, 60. In this study we combine qualitatively different approaches to overcome their limitations and retain their upsides. We use HF trains of short charge-balanced stimulation pulses utilized for the standard HF DBS
--------------------------------------------------------------------------------
chunk_index: 2
chunk_id: PMID_28432303_chunk_0002
token_count: 87
text start:
slowly oscillating stimulation signals of the feedback methods may however cause problems when directly administered to the neuronal tissue as electrical stimulation because of safety aspects like charge density limits18, 59, 60. In this study we combine qualitatively different approaches to overcom
text end:
ectrical stimulation because of safety aspects like charge density limits18, 59, 60. In this study we combine qualitatively different approaches to overcome their limitations and retain their upsides. We use HF trains of short charge-balanced stimulation pulses utilized for the standard HF DBS16, 61

In [13]:
#检查 total_chunks 是否与实际 chunk 数一致
def check_total_chunks_consistency(group):
    actual = len(group)
    recorded = group["total_chunks"].iloc[0]
    return actual == recorded

total_chunks_report = (
    chunks_df.groupby("doc_id")
    .apply(check_total_chunks_consistency)
)

print("Documents with correct total_chunks:", total_chunks_report.sum())
print("Documents with inconsistent total_chunks:", (~total_chunks_report).sum())

Documents with correct total_chunks: 28246
Documents with inconsistent total_chunks: 0

C:\Users\xukeh\AppData\Local\Temp\ipykernel_27620\766120934.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(check_total_chunks_consistency)

In [14]:
#检查标题是否保留
title_samples = chunks_df.sample(10, random_state=42)

for _, row in title_samples.iterrows():
    print("=" * 100)
    print("chunk_id:", row["chunk_id"])
    print("doc_id:", row["doc_id"])
    print("source_title:", row["source_title"])
    print("text preview:")
    print(row["text"][:500])

====================================================================================================
chunk_id: PMID_35514340_chunk_0003
doc_id: PMID_35514340
source_title: Surfactant Treatment Shows Higher Correlation Between Ventilator and EIT Tidal Volumes in an RDS Animal Model
text preview:
Title: Surfactant Treatment Shows Higher Correlation Between Ventilator and EIT Tidal Volumes in an RDS Animal Model

. Mann-Whitney U test was used in between-group comparisons. Statistical significance was set at p < 0.05 and SAS version 9.4 (SAS Institute Inc., Cary, NC, United States) as well as the R4.0.4 program was used for analyses. Twenty three newborn pups were harvested from 6 mother rabbits. Five pups were excluded as a result of early death (n = 2) or measurement failure due to pneu
====================================================================================================
chunk_id: PMID_34947312_chunk_0014
doc_id: PMID_34947312
source_title: Evaluation of Functional Features of Lignocellulosic Particle Composites Containing Biopolymer Binders
text preview:
Title: Evaluation of Functional Features of Lignocellulosic Particle Composites Containing Biopolymer Binders

. The density of surface layers became higher in the core when the RC of the particleboard increased. The modulus of rupture (MOR) and modulus of elasticity (MOE) under the three-point bending stress of the investigated panels are presented in Figure 3. As it can be seen, the highest value of MOR (13.5 N mm−2) was found for PS20, while the lowest (1.5 N mm−2) was for PLA12. The referenc
====================================================================================================
chunk_id: PMID_27776339_chunk_0038
doc_id: PMID_27776339
source_title: Generation of CD20-specific TCRs for TCR gene therapy of CD20low B-cell malignancies insusceptible to CD20-targeting antibodies
text preview:
Title: Generation of CD20-specific TCRs for TCR gene therapy of CD20low B-cell malignancies insusceptible to CD20-targeting antibodies

. Louis, MO), 500 IU/ml INF-γ (Boehringer Ingelheim, Ingelheim am Rhein, Germany), and 10% human serum for an additional two days. Macrophages type I and II were in vitro differentiated from CD14+ monocytes. CD14+ monocytes were cultured for 8 days in IMDM containing 10% human serum in the presence of 50 ng/ml GM-CSF or 5 IU/ml CSF-1 (R&D Systems, Minneapolis, M
====================================================================================================
chunk_id: PMID_19094215_chunk_0002
doc_id: PMID_19094215
source_title: Central nervous system Toll-like receptor expression in response to Theiler's murine encephalomyelitis virus-induced demyelination disease in resistant and susceptible mouse strains
text preview:
Title: Central nervous system Toll-like receptor expression in response to Theiler's murine encephalomyelitis virus-induced demyelination disease in resistant and susceptible mouse strains

. Constant, QC, Canada. The C57BL/6 mice are known to be resistant to the TMEV, while the SJL/J mice are susceptible to chronic TMEV infection[7]. All animals were acclimated to standard laboratory conditions (14-h light, 10-h dark cycle; lights on at 06:00 and off at 20:00 h) with free access to rodent chow
====================================================================================================
chunk_id: PMID_32606479_chunk_0094
doc_id: PMID_32606479
source_title: Origin and composition of three heterolithic boulder- and cobble-bearing deposits overlying the Murray and Stimson formations, Gale Crater, Mars
text preview:
Title: Origin and composition of three heterolithic boulder- and cobble-bearing deposits overlying the Murray and Stimson formations, Gale Crater, Mars

. Geomorphic evidence associated with PICLs abutting calving glaciers (Hendy et al., 2000; Hall et al., 2006) has not been observed in the vicinity of the heterolithic deposits either upslope or at the depositional sites. This model proposes fluvial (water dominated) or debris flow (mobilized by mud supporting matrix) transport in which successi
====================================================================================================
chunk_id: PMID_27935973_chunk_0020
doc_id: PMID_27935973
source_title: The Effects of Compensatory Scanning Training on Mobility in Patients with Homonymous Visual Field Defects: Further Support, Predictive Variables and Follow-Up
text preview:
Title: The Effects of Compensatory Scanning Training on Mobility in Patients with Homonymous Visual Field Defects: Further Support, Predictive Variables and Follow-Up

. The questionnaire data are presented in Table 3 and Fig 4. For all three questionnaires, test scores changed significantly between T-pre, T-post, and FU (F(2,41) = 20.25, P < .001). Compared to T-pre, scores on all three questionnaires had significantly improved at the time of FU (all P < .001, medium effect sizes for IMQ and CV
====================================================================================================
chunk_id: PMID_34138873_chunk_0010
doc_id: PMID_34138873
source_title: Psychometric properties of the brief self-report questionnaire for screening putative pre-psychotic states and validation of clinical utility in young adult
text preview:
Title: Psychometric properties of the brief self-report questionnaire for screening putative pre-psychotic states and validation of clinical utility in young adult

. Together, they can explain 52% of the variance of NS. NS addresses four items referring to feelings of tiredness, lethargy and concentration difficulty. These descriptions are similar to some of the symptoms of a depression episode. Our findings showed that there was a strong association between depression and NS. Finally, we found
====================================================================================================
chunk_id: PMID_28387323_chunk_0023
doc_id: PMID_28387323
source_title: CSE1L interaction with MSH6 promotes osteosarcoma progression and predicts poor patient survival
text preview:
version 21.0 (SPSS Inc., Chicago, IL, USA). Comparisons between different groups were performed using Chi-square tests. The independent prognostic significance of parameters was estimated using the Cox proportional hazards model, and correlation analysis between CSE1L and MSH6 was performed using the Spearman correlation test. The tumor-free survival time was defined as the period from surgery to the detection of new local lesions
====================================================================================================
chunk_id: PMID_33881650_chunk_0017
doc_id: PMID_33881650
source_title: An endophytic Schizophyllum commune Fr. exhibits in-vitro and in-vivo antidiabetic activity in streptozotocin induced diabetic rats
text preview:
Title: An endophytic Schizophyllum commune Fr. exhibits in-vitro and in-vivo antidiabetic activity in streptozotocin induced diabetic rats

. Good inhibitory activity above 80% was demonstrated by four endophytic cultures T1b, B2b, Sch1, and M1a isolated from Ocimum tenuiflorum, Aegle marmelos, Aloe vera, Lawsonia inermis respectively. The IC50 values of these cultures were also determined (Table 1). Morphological analysis revealed T1b, B2b, and M1a as species of Alternaria. Sch1 a non-sporulati
====================================================================================================
chunk_id: PMID_32527044_chunk_0001
doc_id: PMID_32527044
source_title: Ecometabolomics for a Better Understanding of Plant Responses and Acclimation to Abiotic Factors Linked to Global Change
text preview:
the most frequently used platform in ecometabolomics of plants. To gain structural elucidation power, the method of collision-induced dissociation can be used [11], giving rise to the fragment spectrum (MS/MS method) [12]. Fourier-transform ion cyclotron resonance mass spectrometry (FT-ICR-MS) can be used to further increase the number of detectable metabolites

## 检查重叠窗口

In [15]:
# 找出多块文档
multi_doc_ids = (
    chunks_df[chunks_df["total_chunks"] > 1]["doc_id"]
    .drop_duplicates()
    .tolist()
)

# 随机抽取 5 篇多块文档
sample_doc_ids = random.sample(
    multi_doc_ids,
    k=min(5, len(multi_doc_ids))
)

for doc_id in sample_doc_ids:
    doc_chunks = (
        chunks_df[chunks_df["doc_id"] == doc_id]
        .sort_values("chunk_index")
        .reset_index(drop=True)
    )

    print("=" * 120)
    print("doc_id:", doc_id)
    print("source_title:", doc_chunks.loc[0, "source_title"])
    print("total_chunks:", doc_chunks.loc[0, "total_chunks"])

    # 每篇文档最多检查前 3 对相邻 chunk
    max_pairs = min(3, len(doc_chunks) - 1)

    for i in range(max_pairs):
        chunk_a = doc_chunks.loc[i, "text"]
        chunk_b = doc_chunks.loc[i + 1, "text"]

        print("-" * 100)
        print(f"Chunk {i} END:")
        print(chunk_a[-800:])

        print("\n")
        print(f"Chunk {i + 1} START:")
        print(chunk_b[:800])

========================================================================================================================
doc_id: PMID_25003337
source_title: Exposure to Silica Nanoparticles Causes Reversible Damage of the Spermatogenic Process in Mice
total_chunks: 31
----------------------------------------------------------------------------------------------------
Chunk 0 END:
oth the testis and prostate in male offsprings and disrupted the endocrine activity of the male reproductive system by decreasing the levels of testosterone, progesterone and corticosterone in the serum [6]. However, Ramdhan et al [7] found that the exposure to a low concentration of diesel exhaust rich in nanoparticles increased the levels of plasma testosterone, which contradict to Li et al.'s report [6]. The human male reproductive system is known to be vulnerable to many exogenous materials [8]. Additionally, oxidative stress is known to be one of the main mechanisms of this deterioration [9]. Others and we have attributed silica nanoparticle-induced cytotoxicity to oxidative stress [10]–[12]. However, the effects of silica nanoparticles on the male spermatogenic process remain unclear


Chunk 1 START:
Title: Exposure to Silica Nanoparticles Causes Reversible Damage of the Spermatogenic Process in Mice

. Additionally, oxidative stress is known to be one of the main mechanisms of this deterioration [9]. Others and we have attributed silica nanoparticle-induced cytotoxicity to oxidative stress [10]–[12]. However, the effects of silica nanoparticles on the male spermatogenic process remain unclear. The generation of sperm has a a fixed time period in mice, in which the time course of spermatogenesis (from initial meiosis to sperm release into the seminiferous tubule) is approximately 35 days, and the process of sperm movement from the seminiferous tubule into the epididymis to form mature sperm requires a minimum of approximately 2 weeks [13]. In this study, because of the spermatogenesis
----------------------------------------------------------------------------------------------------
Chunk 1 END:
a stainless steel mesh lid in a ventilated room. The mice were maintained at a constant temperature of 20±2°C and a relative humidity of 60±10%, with a 12:12 light/dark cycle. The pad was changed twice per week. All of the mice were provided food and drinking water ad libitum. The animal feed was provided by Beijing Keao Xieli Feedstuff Co., Ltd. The experiments were initiated after a 1-week acclimation period. Before treatment, the mice were fasted overnight. After 1 week of adaptation to laboratory conditions, 48 healthy adult mice with body weights ranging from 20–23 g were randomly divided into control group and silica nanoparticle group with 24 mice per group, with three evaluation time points (days 15, 35 and 60 after the first dose) per group. Four animals per cage were marked using


Chunk 2 START:
After 1 week of adaptation to laboratory conditions, 48 healthy adult mice with body weights ranging from 20–23 g were randomly divided into control group and silica nanoparticle group with 24 mice per group, with three evaluation time points (days 15, 35 and 60 after the first dose) per group. Four animals per cage were marked using trinitrophenol
----------------------------------------------------------------------------------------------------
Chunk 2 END:
After 1 week of adaptation to laboratory conditions, 48 healthy adult mice with body weights ranging from 20–23 g were randomly divided into control group and silica nanoparticle group with 24 mice per group, with three evaluation time points (days 15, 35 and 60 after the first dose) per group. Four animals per cage were marked using trinitrophenol


Chunk 3 START:
Title: Exposure to Silica Nanoparticles Causes Reversible Damage of the Spermatogenic Process in Mice

. Four animals per cage were marked using trinitrophenol. The mice were administered injections of the vehicle control and silica nanoparticles via the tail vein every 3 days, five times over 13 days. Each dose of amorphous silica nanoparticles was 20 mg/kg, and the nanoparticles, which had diameters of 64 nm, were dissolved in physiological saline to obtain a mass concentrations of 12 g/L. Because silica nanoparticales were used as a carrier system in drug delivery as well as getting in blood from environmental exposure, the intravenous administration route of the vehicle injection was selected. The dosage of 20 mg/kg per was based on the previous results of acute toxicity studies [14].
========================================================================================================================
doc_id: PMID_24204912
source_title: Predictors of CD4:CD8 Ratio Normalization and Its Effect on Health Outcomes in the Era of Combination Antiretroviral Therapy
total_chunks: 17
----------------------------------------------------------------------------------------------------
Chunk 0 END:
th cART for reasons that are unclear [12]. Some hypothesize that lymphocyte activation and subpopulation changes, interleukin effects, co-infections, and immunosenescence may play roles [13]. It would be expected that more HIV-positive individuals should achieve CD4:CD8 normalization in the era of effective modern cART, but the extent of ratio normalization among cART treated patients has yet to be described in a large cohort of patients. The primary objective of our study was to determine the incidence and clinical predictors of CD4:CD8 ratio normalization after initiating cART. Our secondary objective was to determine if CD4:CD8 ratio could have an additional role as a prognostic marker for improved health outcomes with respect to developing AIDS-defining illness or death from all causes


Chunk 1 START:
Title: Predictors of CD4:CD8 Ratio Normalization and Its Effect on Health Outcomes in the Era of Combination Antiretroviral Therapy

. The primary objective of our study was to determine the incidence and clinical predictors of CD4:CD8 ratio normalization after initiating cART. Our secondary objective was to determine if CD4:CD8 ratio could have an additional role as a prognostic marker for improved health outcomes with respect to developing AIDS-defining illness or death from all causes. The human subjects activities of the Canadian Observational Cohort (CANOC) have been approved by the Simon Fraser University Research Ethics Board and the University of British Columbia Research Ethics Board as well as the local institutional review boards at each of the participating cohorts, as follows:
----------------------------------------------------------------------------------------------------
Chunk 1 END:
spital but no specific study related consent); MLMC (REB has approved the anonymous use of data retrospectively abstracted from clinical care databases without requiring consent); and EARTH (REB approved the anonymous use of data retrospectively abstracted from clinical care databases without requiring consent; patients signed a general waiver on opening a medical chart at the hospital but no specific study related consent). CANOC included antiretroviral naïve HIV-positive individuals who initiated cART on or after January 1, 2000 from 8 participating cohorts in British Columbia, Ontario and Quebec. Individuals from each cohort were eligible for inclusion into CANOC if they met the following criteria: documented HIV infection, 18 years of age and older, and had at least 1 measurement of CD


Chunk 2 START:
included antiretroviral naïve HIV-positive individuals who initiated cART on or after January 1, 2000 from 8 participating cohorts in British Columbia, Ontario and Quebec. Individuals from each cohort were eligible for inclusion into CANOC if they met the following criteria: documented HIV infection, 18 years of age and older, and had at least 1 measurement of CD4+ T-cell count and HIV RNA within 6 months of initiating cART
----------------------------------------------------------------------------------------------------
Chunk 2 END:
included antiretroviral naïve HIV-positive individuals who initiated cART on or after January 1, 2000 from 8 participating cohorts in British Columbia, Ontario and Quebec. Individuals from each cohort were eligible for inclusion into CANOC if they met the following criteria: documented HIV infection, 18 years of age and older, and had at least 1 measurement of CD4+ T-cell count and HIV RNA within 6 months of initiating cART


Chunk 3 START:
Title: Predictors of CD4:CD8 Ratio Normalization and Its Effect on Health Outcomes in the Era of Combination Antiretroviral Therapy

. Individuals from each cohort were eligible for inclusion into CANOC if they met the following criteria: documented HIV infection, 18 years of age and older, and had at least 1 measurement of CD4+ T-cell count and HIV RNA within 6 months of initiating cART. Patient selection and data extraction were performed locally at the data centers of participating cohorts and pooled at the Project Data Centre in Vancouver, British Columbia. Further details of the participating cohorts and the CANOC structure are described elsewhere [14]. Participants were included in this analysis if they had at least 1 CD4:CD8 ratio measurement within 2 years prior to starting cART (d
========================================================================================================================
doc_id: PMID_29135953
source_title: Spatial-Temporal Dynamics of Cropping Frequency in Hubei Province over 2001–2015
total_chunks: 17
----------------------------------------------------------------------------------------------------
Chunk 0 END:
le cropping areas on a large scale. Moderate spatial resolution time-series vegetation indices have successful applications on crop mapping in Brazil [7,8,9,10], Thailand [11], Vietnam [12,13], Italy [14], Canada [15], USA [16,17], Laurentian Great Lakes Basin [18], Central Asia [19], Africa [20,21], Europe [22] and China [23,24,25,26]. Lunetta et al. [18] examined the crop rotational patterns across the Great Lakes Basin using map products derived from MODIS-NDVI (Normalized Difference Vegetation Index) data. Ding et al. [25] extracted and analyzed the spatial and temporal changes of multiple cropping index from 1999 to 2013 in China using 10-day SPOT time-series (NDVI). MODIS data has the advantages of frequent coverage and moderate spatial resolution and is suitable for mapping cropping


Chunk 1 START:
MODIS-NDVI (Normalized Difference Vegetation Index) data. Ding et al. [25] extracted and analyzed the spatial and temporal changes of multiple cropping index from 1999 to 2013 in China using 10-day SPOT time-series (NDVI). MODIS data has the advantages of frequent coverage and moderate spatial resolution and is suitable for mapping cropping frequency at regional and national scales
----------------------------------------------------------------------------------------------------
Chunk 1 END:
MODIS-NDVI (Normalized Difference Vegetation Index) data. Ding et al. [25] extracted and analyzed the spatial and temporal changes of multiple cropping index from 1999 to 2013 in China using 10-day SPOT time-series (NDVI). MODIS data has the advantages of frequent coverage and moderate spatial resolution and is suitable for mapping cropping frequency at regional and national scales


Chunk 2 START:
Title: Spatial-Temporal Dynamics of Cropping Frequency in Hubei Province over 2001–2015

. Ding et al. [25] extracted and analyzed the spatial and temporal changes of multiple cropping index from 1999 to 2013 in China using 10-day SPOT time-series (NDVI). MODIS data has the advantages of frequent coverage and moderate spatial resolution and is suitable for mapping cropping frequency at regional and national scales. Most previous MODIS-NDVI crop mapping applications have focused on single year crop mapping [18] or single crop system. The crop patterns have been intensively investigated in Northeast or North China in previous studies, however there has been few studies in Central and South China. China has a vast territory width with significantly varied natural environments. Crop rotation,
----------------------------------------------------------------------------------------------------
Chunk 2 END:
system using time-series MODIS data in Hubei Province. The specific objectives include: (1) Developing a hierarchical clustering method (HCM) to map cropping frequency based on time-series MODIS data; (2) Introducing statistics method to measure the change trend of cropping frequency, including change direction and their significance level; (3) Analysis of the spatial-temporal patterns of cropping frequency, obtaining the knowledge of the crop system in Hubei Province, providing a basis for agriculture management. The novelty of the research is that, a HCM with two-stage unsupervised classification was proposed to map the cropping frequency. Key phenological parameters, including the start of season (SOS), the end of season (EOS) and the length of season (LOS), were extracted using dynamic


Chunk 3 START:
, obtaining the knowledge of the crop system in Hubei Province, providing a basis for agriculture management. The novelty of the research is that, a HCM with two-stage unsupervised classification was proposed to map the cropping frequency. Key phenological parameters, including the start of season (SOS), the end of season (EOS) and the length of season (LOS), were extracted using dynamic threshold methods
========================================================================================================================
doc_id: PMID_32907680
source_title: Responding to the Psychological Needs of Health Workers During Pandemic: Ten Lessons From Humanitarian Work
total_chunks: 20
----------------------------------------------------------------------------------------------------
Chunk 0 END:
le 10 lessons that carry significance to shaping response to the pandemic (Table 1). Further research is needed to better understand the unique psychological needs of the health providers during the pandemic, and to develop the effective evidence-based systems of interventions and supports. TABLE 1Ten Lessons from Humanitarian Response to Complex Emergency1. It Is Impossible to Prepare for CEs, but Their Impact Can Be Mitigated: A Perfect StormThe impact of CE is complicated by the disruption in the fabric of social life, and the health providers are being a part of the affected community2. CEs Remind Health Professionals About Their Mission and PurposeWhen responding to CE, providers get the opportunity to directly contribute to transformative change in the society and health-care system3


Chunk 1 START:
Title: Responding to the Psychological Needs of Health Workers During Pandemic: Ten Lessons From Humanitarian Work

. CEs Remind Health Professionals About Their Mission and PurposeWhen responding to CE, providers get the opportunity to directly contribute to transformative change in the society and health-care system3. Frontline Workers Have Different Psychological Needs in Different Phases of the EmergencyResponders have different psychological needs during the Mobilization, Resistance, and Reentry phases of the pandemic response4. Some Stressors Are Worse Than Others: “Don’t Call Us Heroes”Uncertainty about the future, a sense of helplessness, worries about family’s safety, and problematic social supports can leave responders emotionally drained and physically exhausted5. Peer SupportPe
----------------------------------------------------------------------------------------------------
Chunk 1 END:
y risks, and suicidal ideations10. It Is Easier to Adapt to Emergency Than to ReentryVarious studies of emergency responders have demonstrated that reentry, if not addressed, has been associated with increased risks for substance abuse, depression, family breakup, and suicidal behavior Ten Lessons from Humanitarian Response to Complex Emergency A CE is a type of disaster event that is caused by and results in a complicated set of social, medical, and often political circumstances, usually leading to great human suffering and death, and requiring a broad and integrated response.3 Often, CEs occur in the context of war or epidemic; other examples include the Chernobyl disaster in 1986, the cholera epidemic in Haiti in 2010, Fukushima disaster in 2011, and the 2014-2016 Ebola epidemic in West


Chunk 2 START:
human suffering and death, and requiring a broad and integrated response.3 Often, CEs occur in the context of war or epidemic; other examples include the Chernobyl disaster in 1986, the cholera epidemic in Haiti in 2010, Fukushima disaster in 2011, and the 2014-2016 Ebola epidemic in West Africa
----------------------------------------------------------------------------------------------------
Chunk 2 END:
human suffering and death, and requiring a broad and integrated response.3 Often, CEs occur in the context of war or epidemic; other examples include the Chernobyl disaster in 1986, the cholera epidemic in Haiti in 2010, Fukushima disaster in 2011, and the 2014-2016 Ebola epidemic in West Africa


Chunk 3 START:
Title: Responding to the Psychological Needs of Health Workers During Pandemic: Ten Lessons From Humanitarian Work

. Although the scale of the system failure in low-resource settings that already struggle with lack of resources cannot be compared with the robust health-care systems in developed countries, conceptualizing the COVID-19 pandemic as a form of CE allows for placing the challenges of the response into a broader context. Various CEs share similar characteristics4:It is impossible to be fully prepared for a CE.Its impact on the community and the responders is systemic and multilevel.It’s impact profoundly disrupts the fabric of social life.It overwhelms human resources, infrastructure, and logistic capability.Its responders can be the members of the same community and are subject
========================================================================================================================
doc_id: PMID_34001981
source_title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification
total_chunks: 32
----------------------------------------------------------------------------------------------------
Chunk 0 END:
fication has been proposed following the ultra-low emission transformation. Ultra-low emission requires high efficiency in controlling NOx removal, and wide-load denitrification requires the denitrification device to operate under the complex conditions. When the flue gas temperature is low, the denitrification efficiency is low, which leads to an increase in ammonia escape. At the same time, to ensure a higher denitrification efficiency, the amount of ammonia injection is often increased, or the ammonia injection is not adjusted in time when the load fluctuates, which may easily cause excessive ammonia injection15. More, these factors can all lead to an increase in ammonia escape. The escaped ammonia will promote the production of more ABS, and ABS is an important factor in catalyst block


Chunk 1 START:
same time, to ensure a higher denitrification efficiency, the amount of ammonia injection is often increased, or the ammonia injection is not adjusted in time when the load fluctuates, which may easily cause excessive ammonia injection15. More, these factors can all lead to an increase in ammonia escape. The escaped ammonia will promote the production of more ABS, and ABS is an important factor in catalyst blockage and decreased activity
----------------------------------------------------------------------------------------------------
Chunk 1 END:

In [16]:
#检查空文本
print("Chunks with empty text:", (
    chunks_df["text"]
    .astype(str)
    .str.strip()
    .eq("")
).sum())

Chunks with empty text: 0

In [17]:
#检查token长度小于40的chunk
chunks_df[
    chunks_df["token_count"]<40
]

short = chunks_df[
    chunks_df["token_count"]<40
]

print(len(short))
short.sample(5)

25

,chunk_id,text,doc_id,chunk_index,total_chunks,source_title,journal,pub_date,pmid,token_count,split_strategy
229528,PMID_30800380_chunk_0018,Title: Orientation-invariance of individual di...,PMID_30800380,18,36,Orientation-invariance of individual differenc...,Royal Society Open Science,2019,30800380,35,sliding_window
213170,PMID_30430418_chunk_0029,Title: The Combined Effects of Cr(III) Supplem...,PMID_30430418,29,50,The Combined Effects of Cr(III) Supplementatio...,Biological Trace Element Research,2018,30430418,36,sliding_window
159161,PMID_30911046_chunk_0040,Title: On the stress-strain alignment in premi...,PMID_30911046,40,59,On the stress-strain alignment in premixed tur...,Scientific Reports,2019,30911046,37,sliding_window
640132,DOC_3dc7c7b36355_chunk_0015,Title: Research on fault diagnosis method of p...,DOC_3dc7c7b36355,15,33,Research on fault diagnosis method of planetar...,Scientific Reports,2022,,38,sliding_window
268199,PMID_36508026_chunk_0029,Title: Decentralized collaborative multi-insti...,PMID_36508026,29,54,Decentralized collaborative multi-institutiona...,European Journal of Nuclear Medicine and Molec...,2022,36508026,39,sliding_window

In [18]:
#检查是否截断严重
sample = chunks_df.sample(
    10,
    random_state=42
)

for _, row in sample.iterrows():

    print("="*80)

    print(
        row["chunk_id"]
    )

    print("\nBEGIN:")

    print(
        row["text"][:250]
    )

    print("\nEND:")

    print(
        row["text"][-250:]
    )

================================================================================
PMID_35514340_chunk_0003

BEGIN:
Title: Surfactant Treatment Shows Higher Correlation Between Ventilator and EIT Tidal Volumes in an RDS Animal Model

. Mann-Whitney U test was used in between-group comparisons. Statistical significance was set at p < 0.05 and SAS version 9.4 (SAS I

END:
es are shown in Table 1. * means statistical significance between the untreated preterm group and surfactant treated preterm group (p = 0.018, 0.026, Mann-Whitney U test). PIP, peak inspiratory pressure; Inf, inflation; Def, deflation. An increase in
================================================================================
PMID_34947312_chunk_0014

BEGIN:
Title: Evaluation of Functional Features of Lignocellulosic Particle Composites Containing Biopolymer Binders

. The density of surface layers became higher in the core when the RC of the particleboard increased. The modulus of rupture (MOR) and modu

END:
 sample does not experience shear failure during the static bending test [47]. According to statistical analysis, there are no significant differences between the average values of the MOR results for PCL15–20, PLA15–20, and between UF and PS binders
================================================================================
PMID_27776339_chunk_0038

BEGIN:
Title: Generation of CD20-specific TCRs for TCR gene therapy of CD20low B-cell malignancies insusceptible to CD20-targeting antibodies

. Louis, MO), 500 IU/ml INF-γ (Boehringer Ingelheim, Ingelheim am Rhein, Germany), and 10% human serum for an addi

END:
shed twice before use in experiments. All peptides were synthesized in-house using standard Fmoc chemisty. Recombinant HLA-A2 or HLA-B7 heavy chain and human β2m light chain were in-house produced in Escherichia coli. Major histocompatibility complex
================================================================================
PMID_19094215_chunk_0002

BEGIN:
Title: Central nervous system Toll-like receptor expression in response to Theiler's murine encephalomyelitis virus-induced demyelination disease in resistant and susceptible mouse strains

. Constant, QC, Canada. The C57BL/6 mice are known to be res

END:
ith the TMEV, when the infection and demyelination is thought to be well established (see Fig. 1). Theiler's murine encephalomyelitis virus infection can be established in resistant C57BL/6 mice following lipopolysaccharide intraperitoneal injections
================================================================================
PMID_32606479_chunk_0094

BEGIN:
Title: Origin and composition of three heterolithic boulder- and cobble-bearing deposits overlying the Murray and Stimson formations, Gale Crater, Mars

. Geomorphic evidence associated with PICLs abutting calving glaciers (Hendy et al., 2000; Hall e

END:
, although ventifact shaping of the surface particles is common and obscures the original shapes of many of the larger boulders. The limited exposure on the edge of the deposits does not show matrix-supported clasts (as typifies debris flow deposits)
================================================================================
PMID_27935973_chunk_0020

BEGIN:
Title: The Effects of Compensatory Scanning Training on Mobility in Patients with Homonymous Visual Field Defects: Further Support, Predictive Variables and Follow-Up

. The questionnaire data are presented in Table 3 and Fig 4. For all three questio

END:
rmance in daily life as reported by the patients and mobility performance as measured in the Tracking Task and obstacle course (rIMQ(pre)—TT-RT-all(pre) = .158, P = .307; rIMQ(pre)–DSR-all(pre) = .054, P = .732; rIMQ(pre)–PPWS(pre) = -.013, P = .936)
================================================================================
PMID_34138873_chunk_0010

BEGIN:
Title: Psychometric properties of the brief self-report questionnaire for screening putative pre-psychotic states and validation of clinical utility in young adult

. Together, they can explain 52% of the variance of NS. NS addresses four items refer

END:
est reliability, similar to findings of Müller et al. [21]. However, the study has two limitations. First, our subjects were undergraduate college students, and whether the findings could be generalized to other young populations remains to be tested
================================================================================
PMID_28387323_chunk_0023

BEGIN:
version 21.0 (SPSS Inc., Chicago, IL, USA). Comparisons between different groups were performed using Chi-square tests. The independent prognostic significance of parameters was estimated using the Cox proportional hazards model, and correlation anal

END:
ted using the Cox proportional hazards model, and correlation analysis between CSE1L and MSH6 was performed using the Spearman correlation test. The tumor-free survival time was defined as the period from surgery to the detection of new local lesions
================================================================================
PMID_33881650_chunk_0017

BEGIN:
Title: An endophytic Schizophyllum commune Fr. exhibits in-vitro and in-vivo antidiabetic activity in streptozotocin induced diabetic rats

. Good inhibitory activity above 80% was demonstrated by four endophytic cultures T1b, B2b, Sch1, and M1a isol

END:
nce has been submitted to GenBank under the accession number MN475198. On account of the observed morphological and molecular characteristics, strain Sch1 could be identified to be Schizophyllum commune (Fig. 1d). The isolate Schizophyllum commune Fr
================================================================================
PMID_32527044_chunk_0001

BEGIN:
the most frequently used platform in ecometabolomics of plants. To gain structural elucidation power, the method of collision-induced dissociation can be used [11], giving rise to the fragment spectrum (MS/MS method) [12]. Fourier-transform ion cyclo

END:
of collision-induced dissociation can be used [11], giving rise to the fragment spectrum (MS/MS method) [12]. Fourier-transform ion cyclotron resonance mass spectrometry (FT-ICR-MS) can be used to further increase the number of detectable metabolites

In [19]:
#检查overlap是否正常
doc = chunks_df[
    chunks_df["doc_id"]==doc_id
].sort_values("chunk_index")

for i in range(len(doc)-1):

    print("="*80)

    print("Chunk",i)

    print(doc.iloc[i]["text"][-200:])

    print()

    print("Chunk",i+1)

    print(doc.iloc[i+1]["text"][:200])

================================================================================
Chunk 0
ve ammonia injection15. More, these factors can all lead to an increase in ammonia escape. The escaped ammonia will promote the production of more ABS, and ABS is an important factor in catalyst block

Chunk 1
same time, to ensure a higher denitrification efficiency, the amount of ammonia injection is often increased, or the ammonia injection is not adjusted in time when the load fluctuates, which may easil
================================================================================
Chunk 1
re, these factors can all lead to an increase in ammonia escape. The escaped ammonia will promote the production of more ABS, and ABS is an important factor in catalyst blockage and decreased activity

Chunk 2
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. More, these factors can all lead to an increase in ammonia escape. The escaped a
================================================================================
Chunk 2
y measured the ammonium concentration by spectrophotometry18. However, due to the complexity of the composition of the ammonium sulfate salt, the results obtained by only measuring the ammonia content

Chunk 3
ABS deposited on the catalyst surface, Yang crushed the catalyst, weighed a certain mass, added sodium hydroxide, heated to evaporate and then absorbed ammonia with a dilute sulfuric acid solution, an
================================================================================
Chunk 3
r, due to the complexity of the composition of the ammonium sulfate salt, the results obtained by only measuring the ammonia content cannot accurately represent the ABS content on the catalyst surface

Chunk 4
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. However, due to the complexity of the composition of the ammonium sulfate salt,
================================================================================
Chunk 4
 only ammonium sulfate, the total amount is 0.5 N0.5 N < M < NProducts are N–M ammonium sulfate, 2 M-N ammonium hydrogen sulfate Composition analysis method of ammonium sulfate and ammonium bisulfate.

Chunk 5
M ≥ NThe product is only ammonium bisulfate, the total amount is NM ≤ 0.5 NThe product is only ammonium sulfate, the total amount is 0.5 N0.5 N < M < NProducts are N–M ammonium sulfate, 2 M-N ammonium
================================================================================
Chunk 5
nium sulfate, the total amount is 0.5 N0.5 N < M < NProducts are N–M ammonium sulfate, 2 M-N ammonium hydrogen sulfate Composition analysis method of ammonium sulfate and ammonium bisulfate. Liu et al

Chunk 6
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Liu et al. summarized the collection and detection methods of SO321. Zhang Yu in
================================================================================
Chunk 6
lue gas. ABS will affect denitrification through its direct reaction with NO and its interaction with the catalyst. At the macro level, the impact of ABS on denitrification is reflected in the changes

Chunk 7
5130HSO4− 1174 cm−1 29 Collection methods. Analysis methods. ABS comes from the reaction of sulfur oxides and NH3 in the flue gas. ABS will affect denitrification through its direct reaction with NO a
================================================================================
Chunk 7
 through its direct reaction with NO and its interaction with the catalyst. At the macro level, the impact of ABS on denitrification is reflected in the changes in denitrification efficiency. Yu et al

Chunk 8
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Analysis methods. ABS comes from the reaction of sulfur oxides and NH3 in the fl
================================================================================
Chunk 8
ill reduce its denitrification efficiency, as shown in Fig. 2.Figure 2The influence of ABS on V-Ti catalyst denitrification efficiency. The influence of ABS on V-Ti catalyst denitrification efficiency

Chunk 9
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Since the V-Ti catalyst does not have good resistance to ABS poisoning at 350℃,
================================================================================
Chunk 9
 transfer statusRedoxAnalytical methodDenitrification activity testBET characterizationNH3-TPDXPS(X-ray photoelectron spectroscopy)H2-TPD; NH3 and NO oxidation; DRIFTS of NO + O230 Research methods of

Chunk 10
.Table 4Research methods of ABS influence on catalyst.Catalyst propertiesSCR activitySpecific surface area and pore volumeAcidicElectron transfer statusRedoxAnalytical methodDenitrification activity t
================================================================================
Chunk 10
tical methodDenitrification activity testBET characterizationNH3-TPDXPS(X-ray photoelectron spectroscopy)H2-TPD; NH3 and NO oxidation; DRIFTS of NO + O230 Research methods of ABS influence on catalyst

Chunk 11
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Zhang performed BET characterization of the ABS-loaded SCR catalyst prepared by
================================================================================
Chunk 11
 the surface of the catalyst and caused the catalyst to poison and block33. Wang et al. believed that the inhibitory effect of ABS on catalyst activity is reflected in the reaction with Ti to generate

Chunk 12
the denitrification temperature window is usually 300 ~ 400℃. In this temperature range, the sulfuric acid produced by the decomposition of ABS can be adsorbed on the surface of the catalyst and cause
================================================================================
Chunk 12
urface of the catalyst and caused the catalyst to poison and block33. Wang et al. believed that the inhibitory effect of ABS on catalyst activity is reflected in the reaction with Ti to generate TiSO4

Chunk 13
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. In this temperature range, the sulfuric acid produced by the decomposition of AB
================================================================================
Chunk 13
ion study on fouling characteristics10. Liang believed that mixing ABS in fly ash will increase the thermal conductivity of fly ash, and the reason is that ABS increases the particle size of fly ash37

Chunk 14
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Wang Chengyu introduced the fouling model and used Fluent to carry out a softwar
================================================================================
Chunk 14
ermogravimetric-Differential scanning calorimeter) test on fly ash added with ABS, and found that ABS had an effect on the metal oxides in the fly ash, so that the fly ash could be partially melted in

Chunk 15
ium bisulfate content37. Change curve of fly ash adhesion under different ammonium bisulfate content37. Wang conducted a TG-DSC(Thermogravimetric-Differential scanning calorimeter) test on fly ash add
================================================================================
Chunk 15
canning calorimeter) test on fly ash added with ABS, and found that ABS had an effect on the metal oxides in the fly ash, so that the fly ash could be partially melted in the air preheater10. Lu et al

Chunk 16
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Wang conducted a TG-DSC(Thermogravimetric-Differential scanning calorimeter) tes
================================================================================
Chunk 16
ate of PM2.5 is low, so it cannot effectively remove the fine particles formed in the SCR denitration process40. Even though WESP can remove a part of SO3, its ability to remove fine particles is poor

Chunk 17
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Although the dust removal efficiency of the existing ESP of coal-fired power sta
================================================================================
Chunk 17
s of MoO3, leading to a NH4+-HSO4− cation–anion separation by conquering their strong electrostatic interactions. Subsequently the separated NH4+ was consumed by taking part in low-temperature NH3-SCR

Chunk 18
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Chen et al. intercalated the NH4+ of ABS into the interlayers of MoO3, leading t
================================================================================
Chunk 18
 carrier AC has a strong low-temperature reduction ability to H2SO443. Gao Lei found through thermogravimetric experiments that the decomposition temperature of ABS decreased with the addition of WO34

Chunk 19
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. The V2O5/AC(Activated carbon) catalyst with activated coke as the carrier has a
================================================================================
Chunk 19
mparing the decomposition characteristics of ABS loaded on V2O5-MoO3/TiO2 and V2O5-TiO2, it is found that MoO3 will inhibit the release of SO2 and is not conducive to the complete decomposition of ABS

Chunk 20
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. And Ce doping can lower the temperature at which ABS completely decomposes and p
================================================================================
Chunk 20
rcial V-W/Ti catalysts50. Li et al. found that the V/W/Ce/Ti-5% catalyst has better low-temperature reaction activity, and promotes the NH3-SCR of ABS and NO to reduce ABS production and resistance to

Chunk 21
Fe-Nb composite oxide catalyst. It has been industrially used in Wenzhou Power Plant, which has certain advantages compared with traditional commercial V-W/Ti catalysts50. Li et al. found that the V/W
================================================================================
Chunk 21
alysts50. Li et al. found that the V/W/Ce/Ti-5% catalyst has better low-temperature reaction activity, and promotes the NH3-SCR of ABS and NO to reduce ABS production and resistance to ABS poisoning45

Chunk 22
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. It has been industrially used in Wenzhou Power Plant, which has certain advantag
================================================================================
Chunk 22
rmal reduction regeneration W cannot be fully restored4. Yang studied the formation and decomposition characteristics of ABS on the surface of the denitrification catalyst during the full load process

Chunk 23
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Therefore, the activity of the thermal regeneration and thermal reduction cataly
================================================================================
Chunk 23
 and the cold section layer is easily dredged, the waveform is improved from the perspective of the heat transfer element to reduce the energy dissipation rate of the soot blowing and cleaning medium,

Chunk 24
the height of the cold section element is increased above the ABS deposition area (900 mm) and there is a low load and a margin of 50 ~ 100 mm in winter, and the cold section layer is easily dredged,
================================================================================
Chunk 24
rm is improved from the perspective of the heat transfer element to reduce the energy dissipation rate of the soot blowing and cleaning medium, or the enamel element is used to increase the smoothness

Chunk 25
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Replace the practice of blindly increasing soot blowing pressure and frequency w
================================================================================
Chunk 25
ipitator), etc27. According to the position of the ABS control method, the methods of spraying alkali absorbent, blending low-sulfur coal, reducing excess air coefficient, optimizing ammonia injection

Chunk 26
believed that the control of the precursors is an effective method to control ABS56. Zhang summarized the methods of removing SO3 by alkali absorbent, WESP(Wet electrostatic precipitator), etc27. Acco
================================================================================
Chunk 26
 the ABS control method, the methods of spraying alkali absorbent, blending low-sulfur coal, reducing excess air coefficient, optimizing ammonia injection grille and flue gas flow field are summarized

Chunk 27
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Zhang summarized the methods of removing SO3 by alkali absorbent, WESP(Wet elect
================================================================================
Chunk 27
 ABS and SCR generated in the air preheater that migrate to the ABS of the air preheater. Precursor control is from multiple angles such as ammonia injection concentration feedback and precise control

Chunk 28
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. Therefore, by controlling the escape of ammonia to eliminate the problem of ABS
================================================================================
Chunk 28
ABS on air preheater. The precursors regulation and control ABS scheme could be clarified and optimized by taking SCR and air preheater as a whole to study the migration and deposition behavior of ABS

Chunk 29
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. In addition, the existing researches mostly separates SCR and air preheater or s
================================================================================
Chunk 29
ation of ABS increases the concentration of fine particles at the SCR outlet, and some fine particles may penetrate the dust removal equipment and cause fine particles increase in the exhaust flue gas

Chunk 30
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. The generation of ABS increases the concentration of fine particles at the SCR o
================================================================================
Chunk 30
ash. The influence of ABS can be controlled from SCR operating conditions, catalyst modification, catalyst regeneration, modification and flushing optimization of air preheater, and precursors control

Chunk 31
Title: Status and development for detection and control of ammonium bisulfate as a by-product of SCR denitrification

. ABS will also have a certain impact on the properties of fly ash. The influence

In [20]:
#最终质量评估报告
quality_report = {
    "Total Documents": chunks_df["doc_id"].nunique(),
    "Total Chunks": len(chunks_df),
    "Average Chunks per Document": len(chunks_df) / chunks_df["doc_id"].nunique(),
    "Maximum Token Count": chunks_df["token_count"].max(),
    "Chunks >512 Tokens": (chunks_df["token_count"] > 512).sum(),
    "Empty Chunks": (
        chunks_df["text"]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    ),
    "Documents Split": (
        chunks_df.groupby("doc_id")
        .first()["total_chunks"]
        .gt(1)
        .sum()
    )
}

pd.DataFrame(
    quality_report.items(),
    columns=["Metric", "Value"]
)

                        Metric          Value
0              Total Documents   28246.000000
1                 Total Chunks  668461.000000
2  Average Chunks per Document      23.665687
3          Maximum Token Count     513.000000
4           Chunks >512 Tokens       3.000000
5                 Empty Chunks       0.000000
6              Documents Split   27664.000000